import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Layout from "../components/Layout";
import BlockMain from "../components/Blocks/BlockMain";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Loch</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <BlockMain />
      </Layout>
    </>
  );
};

export default Home;
